# -*- coding: utf-8 -*-
Fraud Detection Using Machine Learning
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XraS1V0pU65_dH5hyXHhQf7yUDVLBPJF
"""

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset
df = pd.read_csv('/content/creditcard.csv')

# Data Understanding
print(df.head())
print(df.info())
print(df.describe())
print(df.isnull().sum())

# Handle missing values by dropping rows with NaNs
df.dropna(inplace=True)

# Anomaly Detection
print(df['Class'].value_counts())

sns.countplot(x='Class', data=df)
plt.show()

sns.boxplot(x=df['Amount'])
plt.show()

# Machine Learning Models
X = df.drop('Class', axis=1)
y = df['Class']

from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit_transform(X)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d')
plt.show()

from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)
print("Decision Tree Accuracy:", accuracy_score(y_test, dt_pred))

# Feature Engineering
plt.figure(figsize=(12,8))
sns.heatmap(df.corr())
plt.show()

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

importance = pd.DataFrame({
    'Feature': df.drop('Class', axis=1).columns,
    'Importance': rf.feature_importances_
})

print(importance.sort_values(by='Importance', ascending=False).head(10))

# Real-Time Monitoring
new_transaction = X_test[0:1]

prob = model.predict_proba(new_transaction)[0][1]
print("Fraud Probability:", prob)

if prob > 0.7:
    print("HIGH RISK ALERT")
elif prob > 0.3:
    print("MEDIUM RISK")
else:
    print("LOW RISK")

# Scalability
large_df = pd.concat([df] * 5)

print("Dataset Size:", large_df.shape)

import time
start = time.time()
large_df.describe()
end = time.time()

print("Execution Time:", end - start)

print("Memory Before Optimization:",
      large_df.memory_usage(deep=True).sum()/1024**2, "MB")

large_df['Class'] = large_df['Class'].astype('int8')

print("Memory After Optimization:",
      large_df.memory_usage(deep=True).sum()/1024**2, "MB")

# Final Conclusion
print("Credit Card Fraud Detection Project Completed Successfully")
